Bug fixing
Spielmannmisha/pornhub_api_client pull request #5
Opened 2021-05-08 19:38 UTC by Spielmannmisha

1) Fixed bug with encoding tags

- Tags were added like /search?tags=alan, asyan
-   Now its /search?tags[]=alan, asyan

2) Replaced urllib with requests2 library:
Few changes inside make_request function

3) Now functions return arrays of elements, instead of whole json

2021-05-08 22:57 UTC, qelphybox requested changes
Все круто вроде так, красава. Только теги надо по другому собирать

2021-05-08 22:57 UTC, qelphybox commented on pornhub/client.py
> +            params["tags[]"] = ",".join(tags)
Нужно ведь не через запятую их объединить, нужно `tags[]=alan&tags[]=asyan`

2021-05-09 05:12 UTC, Spielmannmisha commented on pornhub/client.py
> +            params["tags[]"] = ",".join(tags)
Смотри, я наткнулся на такой коммент:
[https://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys/1746566#1746566](url)

Можешь сам протестировать оба вида запросов и оба дадут идентичный результат.

2021-05-09 08:39 UTC, qelphybox commented on pornhub/client.py
> +            params["tags[]"] = ",".join(tags)
Без проблем, если работает то супер.

Дело ведь не в стандарте, поскольку его нет, те кто предоставляют апи обычно предоставляют доки, и в них написано как надо слать запрос со списками. Если доков нет надо самим найти как слать, потому что хз что их сервер умеет просить, а что нет. Отсюда и вопрос был: вдвоем с тобой мы только один формат протестировали, а ты реализовал другой.

2021-05-16 20:30 UTC, finzr commented
всё ок, красава!

2021-05-24 06:55 UTC, merged